### ISSUE TITLE
README.mdに誤字

### ISSUE THREAD

**Issue by Doppon** [chikyuinc/chikyu-sdk-ruby#2]
内容：
> token = Chikyu::Sdk::SecurityToken.create 'token_name', 'emaill', 'password', 86400

部分の emaill を誤字ってる。

URL：
https://github.com/chikyuinc/chikyu-sdk-ruby#%E8%AA%8D%E8%A8%BC%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B

**Comment by ryouzi** [comment]
@Doppon 
ご報告ありがとうございます。
こちら、修正いたしました。
